USE [master]
GO
/****** Object:  Database [MyFirstVisualBasicNetMVC_DB]    Script Date: 3/30/2020 2:36:36 AM ******/
CREATE DATABASE [MyFirstVisualBasicNetMVC_DB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MyFirstVisualBasicNetMVC_DB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\MyFirstVisualBasicNetMVC_DB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'MyFirstVisualBasicNetMVC_DB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\MyFirstVisualBasicNetMVC_DB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [MyFirstVisualBasicNetMVC_DB] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MyFirstVisualBasicNetMVC_DB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [MyFirstVisualBasicNetMVC_DB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [MyFirstVisualBasicNetMVC_DB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [MyFirstVisualBasicNetMVC_DB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [MyFirstVisualBasicNetMVC_DB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [MyFirstVisualBasicNetMVC_DB] SET ARITHABORT OFF 
GO
ALTER DATABASE [MyFirstVisualBasicNetMVC_DB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [MyFirstVisualBasicNetMVC_DB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [MyFirstVisualBasicNetMVC_DB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [MyFirstVisualBasicNetMVC_DB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [MyFirstVisualBasicNetMVC_DB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [MyFirstVisualBasicNetMVC_DB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [MyFirstVisualBasicNetMVC_DB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [MyFirstVisualBasicNetMVC_DB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [MyFirstVisualBasicNetMVC_DB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [MyFirstVisualBasicNetMVC_DB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [MyFirstVisualBasicNetMVC_DB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [MyFirstVisualBasicNetMVC_DB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [MyFirstVisualBasicNetMVC_DB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [MyFirstVisualBasicNetMVC_DB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [MyFirstVisualBasicNetMVC_DB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [MyFirstVisualBasicNetMVC_DB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [MyFirstVisualBasicNetMVC_DB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [MyFirstVisualBasicNetMVC_DB] SET RECOVERY FULL 
GO
ALTER DATABASE [MyFirstVisualBasicNetMVC_DB] SET  MULTI_USER 
GO
ALTER DATABASE [MyFirstVisualBasicNetMVC_DB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [MyFirstVisualBasicNetMVC_DB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [MyFirstVisualBasicNetMVC_DB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [MyFirstVisualBasicNetMVC_DB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [MyFirstVisualBasicNetMVC_DB] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'MyFirstVisualBasicNetMVC_DB', N'ON'
GO
ALTER DATABASE [MyFirstVisualBasicNetMVC_DB] SET QUERY_STORE = OFF
GO
USE [MyFirstVisualBasicNetMVC_DB]
GO
/****** Object:  Table [dbo].[Category]    Script Date: 3/30/2020 2:36:37 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Category](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[CategoryName] [nvarchar](250) NULL,
 CONSTRAINT [PK_Category] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Product]    Script Date: 3/30/2020 2:36:37 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Product](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[ProductName] [nvarchar](100) NULL,
	[Quantity] [int] NULL,
	[CatId] [int] NULL,
 CONSTRAINT [PK_Product] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Product]  WITH CHECK ADD  CONSTRAINT [FK_Product_Category] FOREIGN KEY([CatId])
REFERENCES [dbo].[Category] ([id])
GO
ALTER TABLE [dbo].[Product] CHECK CONSTRAINT [FK_Product_Category]
GO
USE [master]
GO
ALTER DATABASE [MyFirstVisualBasicNetMVC_DB] SET  READ_WRITE 
GO
